pipeline {
    agent any

    environment {
        EC2_IP = "16.176.178.109"
        EC2_USER = "ubuntu"
        PEM_PATH = "D:/DEVOPS/AWS-EC2.pem"
        PM2_APP = "cinema-booking-frontend"
    }

    stages {
        stage('Pull code') {
            steps {
                git branch: 'main', url: 'https://github.com/Cinema-Booking-App/cinema-booking-frontend.git'
            }
        }

        stage('Deploy to EC2') {
            steps {
                bat """
                ssh -o StrictHostKeyChecking=no -i "%PEM_PATH%" %EC2_USER%@%EC2_IP% "cd ~/cinema-booking-frontend && \
                git pull origin main && \
                npm install && \
                npm run build && \
                pm2 restart %PM2_APP%"
                """
            }
        }
    }
}
